/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 cubo.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Cubo(props) {
  const { nodes, materials } = useGLTF('/cubo.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cubo.geometry} material={materials['Material.001']} rotation={[-1.673, -0.092, 0.249]} />
    </group>
  )
}

useGLTF.preload('/cubo.gltf')
