/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 logoElectric.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function LogoElectric(props) {
  const { nodes, materials } = useGLTF('/logoElectric.gltf')
  return (
    <group {...props} dispose={null}>
      <lineSegments geometry={nodes.mesh.geometry} material={materials.material1} />
    </group>
  )
}

useGLTF.preload('/logoElectric.gltf')
